"undefined"==typeof UBM&&(UBM=function(){});
UBM.Beacon=function(c){this._config={environment:"d",apiKey:null};"object"==typeof c&&(this._config=UBM.Beacon.Util.mergeJson(this._config,c));return this};UBM.Beacon.version="0.0.2";UBM.Beacon.environment={d:"http://insights.test:8080",i:"https://insn-dev.techweb.com",u:"https://insu-dev.techweb.com",p:"https://ins.techweb.com"};UBM.Beacon.insightsCookie={d:"Insights-int",i:"Insights-int",u:"Insights-uat",p:"Insights"};UBM.Beacon.endpoints={record:"/beacon/record.do",knownuser:"/beacon/knownUser.do"};
UBM.Beacon.eloquaInstances={2150:{apiKey:"a4a13b6f56bd59edaf35f3c3d6cdf8db47865c2356b941b1ed1b93f97d93177d",visitorDataLookupKey:"f09b5473ef7642a085c28ad29c30c1d2",contactDataLookupKey:"adfe3e321ed34dcbbb8234b89c9eeb28"},657486201:{apiKey:"4cbe664e08e6d44e462abf2e19bc36106d7446eefe7ad11b9ca6b56aa37f6a00",visitorDataLookupKey:"7435f16d0b5c4189a89d0d109d2517f5",contactDataLookupKey:"de49844133f84f629c4792556aff3176"}};
UBM.Beacon.prototype.track=function(c,f,a,d){if("undefined"==typeof c||"undefined"==typeof f||"undefined"==typeof a)return!1;var b=document.createElement("iframe");b.setAttribute("frameborder","0");b.setAttribute("width","0");b.setAttribute("height","0");b.setAttribute("tabindex","-1");b.setAttribute("style","display:none");a="a\x3d"+a;for(var e in f)f.hasOwnProperty(e)&&(a+="\x26"+e+"\x3d"+encodeURIComponent(f[e]));b.src=c+"?"+a;UBM.Beacon.Util.onDocumentReady(function(){"undefined"==typeof d||null===
d?null!==document.body&&document.body.appendChild(b):d.appendChild(b)});return!0};UBM.Beacon.prototype.pageview=function(c,f){var a={};"object"==typeof c&&(c.externalContentId&&(a.e=c.externalContentId),c.ngAssetId&&(a.n=c.ngAssetId));a.u=encodeURIComponent(location.href);a.t="P";this.track(UBM.Beacon.environment[this._config.environment]+UBM.Beacon.endpoints.record,a,this._config.apiKey);this.elqKnownUser()};
UBM.Beacon.prototype.elqKnownUser=function(){var c=this;if("undefined"==typeof UBM.Beacon.Eloqua)return!1;var f=UBM.Beacon.environment[this._config.environment]+UBM.Beacon.endpoints.knownuser,a=[],d;for(d in UBM.Beacon.eloquaInstances)UBM.Beacon.eloquaInstances.hasOwnProperty(d)&&a.push(d);var b=function(){var e=a.pop();if("undefined"!=typeof e&&null!==e){var d=new UBM.Beacon.Eloqua({visitorDataLookupKey:UBM.Beacon.eloquaInstances[e].visitorDataLookupKey,contactDataLookupKey:UBM.Beacon.eloquaInstances[e].contactDataLookupKey});
d&&(d.setSiteId(e),d.getVisitor(function(a){if(a.email){var g={email:a.email};d.getContact(a.email,function(a){a.contactId&&(g.e=a.contactId,c.track(f,g,UBM.Beacon.eloquaInstances[e].apiKey));b()},function(){b()})}else b()},function(){b()}))}};b();return!0};UBM.Beacon.prototype.comment=function(){};UBM.Beacon.prototype.like=function(){};
UBM.Beacon.Eloqua=function(a){this._config={visitorDataLookupKey:null,contactDataLookupKey:null,guidLookupTimeout:3E3,visitorDataLookupTimeout:3E3,contactDataLookupTimeout:3E3};"object"==typeof a&&(this._config=UBM.Beacon.Util.mergeJson(this._config,a));return this};UBM.Beacon.Eloqua.EloquaDataFields={visitor:{email:"V_Email_Address"},contact:{email:"C_EmailAddress",contactId:"ContactIDExt"}};UBM.Beacon.Eloqua.prototype.setSiteId=function(a){_elqQ.push(["elqSetSiteId",a])};
UBM.Beacon.Eloqua.prototype.eloquaLookup=function(a,c,b){if(!a||!c||!b)return!1;var k=b.timeout?b.timeout:3E3;if("object"==typeof _elqQ){_elqQ.push(a);var g=null,d=null;window[c]=null;g=setTimeout(function(){d&&clearInterval(d);"function"==typeof b.failureCallback&&b.failureCallback("timedout")},k);d=setInterval(function(){if("function"==typeof window[c]){var a=window[c];window[c]=null;clearInterval(d);g&&clearTimeout(g);if("function"==typeof b.successCallback)if("object"==typeof b.dataFields){var h=
{},e;for(e in b.dataFields)if(b.dataFields.hasOwnProperty(e)){var f=a(b.dataFields[e]);"string"==typeof f&&0===f.length&&(f=null);h[e]=f}b.successCallback(h)}else b.successCallback(a())}},100)}return!0};UBM.Beacon.Eloqua.prototype.getGUID=function(a,c){this.eloquaLookup(["elqGetCustomerGUID"],"GetElqCustomerGUID",{successCallback:a,failureCallback:c,timeout:this._config.guidLookupTimeout});return!0};
UBM.Beacon.Eloqua.prototype.getVisitor=function(a,c){return this._config.visitorDataLookupKey?(this.eloquaLookup(["elqDataLookup",escape(this._config.visitorDataLookupKey),""],"GetElqContentPersonalizationValue",{successCallback:a,failureCallback:c,timeout:this._config.visitorDataLookupTimeout,dataFields:UBM.Beacon.Eloqua.EloquaDataFields.visitor}),!0):!1};
UBM.Beacon.Eloqua.prototype.getContact=function(a,c,b){return this._config.contactDataLookupKey?(this.eloquaLookup(["elqDataLookup",escape(this._config.contactDataLookupKey),"\x3cC_EmailAddress\x3e"+a+"\x3c/C_EmailAddress\x3e"],"GetElqContentPersonalizationValue",{successCallback:c,failureCallback:b,timeout:this._config.contactDataLookupTimeout,dataFields:UBM.Beacon.Eloqua.EloquaDataFields.contact}),!0):!1};
UBM.Beacon.Util=function(){};UBM.Beacon.Util.mergeJson=function(){if(1>=arguments.length)throw Error("Must provide at least two objects");for(var a={},c=0;c<arguments.length;c++){var b=arguments[c];if("object"!=typeof b)throw Error("Argument "+(c+1)+" is not a valid JSON object");for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d])}return a};
UBM.Beacon.Util.onDocumentReady=function(a){"complete"==document.readyState||"interactive"==document.readyState?"function"==typeof a&&a():document.addEventListener?document.addEventListener("DOMContentLoaded",function(){document.removeEventListener("DOMContentLoaded",arguments.callee,!1);"function"==typeof a&&a()},!1):document.attachEvent&&document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",arguments.callee),"function"==
typeof a&&a())})};UBM.Beacon.Util.cookie=function(){};UBM.Beacon.Util.cookie.load=function(a){if("undefined"==typeof document)return null;var c=null,b=document.cookie;a+="\x3d";0<b.length&&(begin=b.indexOf(a),-1!=begin&&(begin+=a.length,end=b.indexOf(";",begin),-1==end&&(end=b.length),c=unescape(b.substring(begin,end))));return c};
